### ISSUE TITLE
Dark Theme support

### ISSUE THREAD

**Issue by apiszcz** [muratkendir/FilterLayersAtOnce#4]
Dark theme does not show the comparison operator

![image](https://user-images.githubusercontent.com/1430861/87243116-39165e00-c401-11ea-8bb8-25659eecc1e3.png)

**Comment by muratkendir** [comment]
I have enlarged the operator combobox size, because dark theme adds an indent to operator texts. I will check again with v0.7

**Comment by muratkendir** [comment]
Tried again with Fusion theme, in dark mode. Operators are visible now.

**Comment by apiszcz** [comment]
QGIS 3.16

```
020-12-01T21:11:22     WARNING    Traceback (most recent call last):
              File "C:/Users/abc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FilterLayersAtOnce-master\filter_multiple_layers_at_once.py", line 240, in run
              self.dlg = FilterLayersAtOnceDialog()
              File "C:/Users/abc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FilterLayersAtOnce-master\filter_multiple_layers_at_once_dialog.py", line 44, in __init__
              self.setupUi(self)
              File "", line 37, in setupUi
             AttributeError: type object 'QPalette' has no attribute 'PlaceholderText'
```
